version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - ELASTIC_PASSWORD=elastic
            - xpack.security.enabled=true
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - esdata:/usr/share/elasticsearch/data

volumes:
    esdata:
        driver: local
